# Generated by Django 6.0.3 on 2026-03-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='태그명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'db_table': 'escape_tag',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('review', '리뷰'), ('job', '구직'), ('assignment', '양도'), ('make', '창작'), ('suggest', '질문/건의'), ('tip', '꿀팁'), ('team', '대외활동'), ('play', '온라인')], max_length=20, verbose_name='게시판 종류')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, to='board.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'escape_board',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='escape_boar_categor_061c6d_idx')],
            },
        ),
    ]
