# Generated by Django 6.0.3 on 2026-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='카페명')),
                ('address', models.CharField(max_length=256, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('theme_count', models.PositiveIntegerField(default=0, verbose_name='테마 수')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '방탈출 카페',
                'verbose_name_plural': '방탈출 카페',
                'db_table': 'escape_cafe',
            },
        ),
    ]
