# Generated by Django 6.0.3 on 2026-03-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='테마명')),
                ('genre', models.CharField(blank=True, max_length=64, verbose_name='장르')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1~5 사이의 난이도', verbose_name='난이도')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='진행 시간(분)')),
                ('booking_url', models.URLField(blank=True, verbose_name='예약 링크')),
                ('description', models.TextField(blank=True, verbose_name='테마 설명')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='cafe.cafe', verbose_name='카페')),
            ],
            options={
                'verbose_name': '방탈출 테마',
                'verbose_name_plural': '방탈출 테마',
                'db_table': 'escape_theme',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('cafe', 'name'), name='unique_theme_name_per_cafe')],
            },
        ),
    ]
