# Generated by Django 6.0.3 on 2026-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='매장 이미지'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='예: 10:00 ~ 22:00', max_length=128, verbose_name='영업시간'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='region',
            field=models.CharField(blank=True, help_text='홍대, 강남, 건대, 신촌 등', max_length=32, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='theme',
            name='activity_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1~5 사이의 활동성', verbose_name='활동성'),
        ),
        migrations.AddField(
            model_name='theme',
            name='clear_rate',
            field=models.FloatField(default=0.0, help_text='0~100 사이의 탈출 성공률', verbose_name='탈출률(%)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='horror_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1~5 사이의 공포도', verbose_name='공포도'),
        ),
        migrations.AddField(
            model_name='theme',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='최대 인원'),
        ),
        migrations.AddField(
            model_name='theme',
            name='min_players',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='최소 인원'),
        ),
        migrations.AddField(
            model_name='theme',
            name='poster_url',
            field=models.URLField(blank=True, verbose_name='테마 포스터 이미지'),
        ),
        migrations.AddField(
            model_name='theme',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='1인 기준 가격', verbose_name='가격(원)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='rating',
            field=models.FloatField(default=0.0, help_text='0.0~5.0 사이의 평점', verbose_name='평점'),
        ),
        migrations.AddField(
            model_name='theme',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='리뷰 수'),
        ),
    ]
